### ISSUE TITLE
ptr2 as Decoder config option

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [worldline-go/struct2#8]
Greetings,
Me again. Given that you have much bigger experience with this package, how does it sounds having global `ptr2` decoder config option? I do know that ptr2 works implicitly for structs, but what about primitive types.
E.g.:
```
type A struct {
    Age *int
}
```
Doesn't end up as `&int` in the resulting `map[string]any`.

**Comment by rytsh** [comment]
Hi @Dragomir-Ivanov, you mean to give global ptr2 to convert all pointer types?

We can give this as option and it also works in primitive types but you need modify your struct.
```go
type A struct {
    Age *int `struct:"age,ptr2"` // or you can just write -> struct:",ptr2"
}
```

**Comment by Dragomir-Ivanov** [comment]
@rytsh Thank you for your reply. 
Having pointer to primitive type is a way to have an optional field, where primitive default value is a valid value. In your example `age = 0` is a valid one.
Most of the time, the user will not want the pointer into its `map[string]interface{}`, so it makes since `ptr2` to be default for primitive types.

I do know that having the `ptr2` as tag value does the trick, but having to say that explicitly on each pointer to primitive type is error prone and cumbersome.
If you reject this, it is okay. I understand.
